import Script from "next/script";
import localFont from "next/font/local";

import Header from "components/header";

import { ThemeProvider } from "context/theme-context";

import "styles/globals.css";

const sfRegular = localFont({
  src: "./styles/fonts/sf-pro-regular.woff2",
  variable: "--primary-font-family"
});

export const metadata = {
  title: "Norman Sobczyk - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <head>
        <Script src="https://niezleziolko.app/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="76ab2befea841a6bfb153bab-|49" defer />
      </head>
      <body className={`${sfRegular.variable}`}>
        <ThemeProvider>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
};