import localFont from "next/font/local";

import Header from "components/header";

import { ThemeProvider } from "context/theme-context";

import "styles/globals.css";

const sfRegular = localFont({
  src: "./styles/fonts/sf-pro-regular.woff2",
  variable: "--primary-font-family"
});

export const metadata = {
  title: "Norman Sobczyk - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sfRegular.variable}`}>
        <ThemeProvider>
          <Header />
          <main className="mt-11">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
};